### PR TITLE
Fix #543's merge with main: extract the declared repository inside the release boundary

### PR DESCRIPTION
**Pull request by JoviDeCroock**
Targets #543's branch, not `main`. #543's CI is red on a semantic merge conflict — the branch head is fine on its own, so a re-run will not clear it.

## What broke

`main` and #543 each changed `runScanPipeline` without seeing the other, and git merges both cleanly:

- #478 (merged into `main` on Aug 1) added the intent envelope, which reads `resolved.staged.artifact.files` and `diff.stagedManifestText` in `runScanPipeline`.
- #543 moved `resolved` inside `analyzeRelease` so the raw file arrays cannot escape, and drops `diff.stagedManifestText` at that same boundary.

The merge result references a `resolved` that no longer exists in that scope:

```
server/lib/scan/pipeline.ts(135,16): error TS2304: Cannot find name 'resolved'.
```

At runtime every scan throws before a report is generated — `scan.pipeline.failed` with `ReferenceError: resolved is not defined`, then `scan.error.unclassified`. That is 14 failures in `test/scan-pipeline.test.mjs` and 10 in `test/workers/workflow-gate-job.test.ts`, and it is both red jobs on the PR (`lint · format · typecheck · test` and `e2e`).

Reproduced locally by merging `origin/main` (c086064) into the PR head (a2e9522) — the same thing CI builds.

## Why the one-line fix is the wrong one

Swapping `resolved.staged.artifact.files` for a surviving reference would trade a loud failure for a silent one. `analyzeRelease` also sets `diff.stagedManifestText = null`, so `extractDeclaredRepository` would be handed `manifestText: null` and an emptied file array: npm releases would stop declaring a repository, every intent envelope would quietly read `absent`, and nothing would fail.

So the extraction moves to where its inputs are still alive. `summarizeResolvedArtifacts` — already the projection that runs before the release — now also projects `declaredRepository` into `ArtifactFacts`, and `runScanPipeline` reads the fact. `computeDiff` and the projection share a new `readStagedManifestText` helper so the two cannot drift over which file is the manifest.

This keeps #543's invariant intact: `ResolvedArtifacts` still never escapes `analyzeRelease`.

## Tests

- The exact-shape `summarizeResolvedArtifacts` assertion gains `declaredRepository`.
- New cases for both extraction paths: a staged manifest declaring `repository`, and the PyPI `PKG-INFO` `Project-URL: Source` fallback.
- A new `analyzeRelease` test pins the declared repository surviving a boundary that has already emptied the staged file array and nulled `stagedManifestText` — the exact shape of this bug, so a future refactor of the boundary trips a test rather than blanking the envelope.

`pnpm run verify` green on the merge result: 1057 node + 447 worker tests, lint/format/typecheck clean.

e2e was not run here — this sandbox's preinstalled Chromium is build 1194 and the pinned Playwright wants 1228. The e2e job's failures were the same `ReferenceError` in the gate-review smoke path, so it is expected to clear, but CI is the check that proves it.

One unrelated observation: `test/workers/public-diff-routes.test.ts > diff endpoint rate-limits by IP` failed once (expected 429, got 400) in a full-suite run and passed on its own and on a repeat full run. Looks like a timing flake in the shared limiter under load, not related to this change — noting it in case it recurs.

## Docs

- `docs/architecture.md` — `ArtifactFacts` now lists the declared repository, plus a line stating that reading raw evidence after the boundary fails silently rather than loudly.
- `docs/intent-envelope.md` — records where the extraction actually happens, and fixes a stale `server/lib/scan-pipeline.ts` path.

## Merge ordering

Nothing new here: #543's own note about #542 also carrying a `0025` migration still applies.

---
_Generated by [Claude Code](https://claude.ai/code/session_018kDtdqZe8XKoaAnYJY9QZw)_

### CODE REVIEW

**Comment by JoviDeCroock** [comment]
Superseded: the fix was incorporated directly into #543 while rebasing that branch onto current main.
